#!/bin/bash
# Manages the continuous build counter and regenerates src/v1/version_build.h.
# Counter resets only when FIRMWARE_VERSION_MAJOR/MINOR/PATCH changes in version.h.
#
# State file format (src/v1/.build_state):
#   line 1: M.N.P  (version at last build)
#   line 2: N       (build counter)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION_H="$PROJECT_ROOT/src/v1/version.h"
STATE_FILE="$PROJECT_ROOT/src/v1/.build_state"
OUTPUT_FILE="$PROJECT_ROOT/src/v1/version_build.h"

# Read current version components from version.h
MAJOR=$(sed -n 's/^#define FIRMWARE_VERSION_MAJOR[[:space:]]*//p' "$VERSION_H")
MINOR=$(sed -n 's/^#define FIRMWARE_VERSION_MINOR[[:space:]]*//p' "$VERSION_H")
PATCH=$(sed -n 's/^#define FIRMWARE_VERSION_PATCH[[:space:]]*//p' "$VERSION_H")
CURRENT_VERSION="$MAJOR.$MINOR.$PATCH"

if [ -f "$STATE_FILE" ]; then
    STORED_VERSION="$(sed -n '1p' "$STATE_FILE")"
    STORED_COUNT="$(sed -n '2p' "$STATE_FILE")"
    if [ "$STORED_VERSION" = "$CURRENT_VERSION" ]; then
        BUILD_NUMBER=$((STORED_COUNT + 1))
    else
        BUILD_NUMBER=1
    fi
else
    BUILD_NUMBER=1
fi

printf '%s\n%s\n' "$CURRENT_VERSION" "$BUILD_NUMBER" > "$STATE_FILE"

cat > "$OUTPUT_FILE" << EOF
#pragma once
// Auto-generated by scripts/bump_build.sh — do not edit.
#define FIRMWARE_BUILD_NUMBER $BUILD_NUMBER
#define FIRMWARE_VERSION_PATCH_STR "$(printf '%02d' "$PATCH")"
EOF
