#!/bin/bash
# Manages the continuous build counter and regenerates src/v1/version_build.h.
# Counter resets only when FIRMWARE_VERSION_MAJOR (year) or FIRMWARE_VERSION_MINOR
# (month) changes. Patch changes alone do not reset the counter.
#
# State file format (src/v1/.build_state):
#   line 1: MAJOR.MINOR  (year.month at last build, e.g. "26.2")
#   line 2: N             (build counter)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION_H="$PROJECT_ROOT/src/v1/version.h"
STATE_FILE="$PROJECT_ROOT/src/v1/.build_state"
OUTPUT_FILE="$PROJECT_ROOT/src/v1/version_build.h"

# Read current version components from version.h (values have no leading zeros)
MAJOR=$(sed -n 's/^#define FIRMWARE_VERSION_MAJOR[[:space:]]*//p' "$VERSION_H")
MINOR=$(sed -n 's/^#define FIRMWARE_VERSION_MINOR[[:space:]]*//p' "$VERSION_H")
PATCH=$(sed -n 's/^#define FIRMWARE_VERSION_PATCH[[:space:]]*//p' "$VERSION_H")
RELEASE_KEY="$MAJOR.$MINOR"

if [ -f "$STATE_FILE" ]; then
    STORED_KEY="$(sed -n '1p' "$STATE_FILE")"
    STORED_COUNT="$(sed -n '2p' "$STATE_FILE")"
    if [ "$STORED_KEY" = "$RELEASE_KEY" ]; then
        BUILD_NUMBER=$((STORED_COUNT + 1))
    else
        BUILD_NUMBER=1
    fi
else
    BUILD_NUMBER=1
fi

printf '%s\n%s\n' "$RELEASE_KEY" "$BUILD_NUMBER" > "$STATE_FILE"

cat > "$OUTPUT_FILE" << EOF
#pragma once
// Auto-generated by scripts/bump_build.sh — do not edit.
#define FIRMWARE_BUILD_NUMBER $BUILD_NUMBER
#define FIRMWARE_VERSION_MAJOR_STR "$(printf '%02d' "$MAJOR")"
#define FIRMWARE_VERSION_MINOR_STR "$(printf '%02d' "$MINOR")"
#define FIRMWARE_VERSION_PATCH_STR "$(printf '%02d' "$PATCH")"
EOF
