#!/bin/bash
# Manages the daily build counter and regenerates src/v1/version_build.h.
# Run from src/v1/ (the Makefile's working directory).
#
# State file format (src/v1/.build_state):
#   line 1: YYYY-MM-DD (last build date)
#   line 2: N          (build counter for that date)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATE_FILE="$PROJECT_ROOT/src/v1/.build_state"
OUTPUT_FILE="$PROJECT_ROOT/src/v1/version_build.h"

TODAY="$(date +%Y-%m-%d)"

if [ -f "$STATE_FILE" ]; then
    STORED_DATE="$(sed -n '1p' "$STATE_FILE")"
    STORED_COUNT="$(sed -n '2p' "$STATE_FILE")"
    if [ "$STORED_DATE" = "$TODAY" ]; then
        BUILD_NUMBER=$((STORED_COUNT + 1))
    else
        BUILD_NUMBER=1
    fi
else
    BUILD_NUMBER=1
fi

printf '%s\n%s\n' "$TODAY" "$BUILD_NUMBER" > "$STATE_FILE"

cat > "$OUTPUT_FILE" << EOF
#pragma once
// Auto-generated by scripts/bump_build.sh — do not edit.
#define FIRMWARE_BUILD_NUMBER $BUILD_NUMBER
#define FIRMWARE_BUILD_NUMBER_STR "$(printf '%02d' "$BUILD_NUMBER")"
#define FIRMWARE_BUILD_DATE "$TODAY"
EOF
